scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: 'ec2-infra'
    metrics_path: /metrics
    ec2_sd_configs:
      - region: eu-west-2
        port: 9100
        access_key: <key>
        secret_key: <secrets>
        profile: iam-role-instance-profile-arn
        filters:
          - name: tag:prometheus
            values: ['true-web']
    relabel_configs:
      - source_labels: [__meta_ec2_tag_prometheus]
        regex: (.+)
        target_label: instance
        replacement: $1
